### ISSUE TITLE
Mock publication/article item

### ISSUE THREAD

**Issue by espinosajuanma** [Maryzender/maryzender#2]
The item of a publication or article needs to have the following fields:

- Title: `string`
- Date: `date`
- Journal: `string`
- Authors: `[]string`
- Link: `string`

### Requirements

- When **Author** is the same as the site params author it needs to render with bold letters
- Order from newest to oldest
- Add #{N} from the top to the bottom with a countdown

**Comment by Maryzender** [comment]
Please, add the following fields:
- Volume: always are numbers 52, 3(2), etc
- Pages: a range 45-87
- DOI: this address is not the same as the "Link" field
